"""
Django settings for mysite project.

Generated by 'mydjango-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5qi=8@cg0@c=q8x*3hfyhpnckc=p&tc$&6@#9#td-&(c5bj^ow'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'mydjango.contrib.admin',
    'mydjango.contrib.auth',
    'mydjango.contrib.contenttypes',
    'mydjango.contrib.sessions',
    'mydjango.contrib.messages',
    'mydjango.contrib.staticfiles',
    'blog'
]

MIDDLEWARE = [
    'mydjango.middleware.security.SecurityMiddleware',
    'mydjango.contrib.sessions.middleware.SessionMiddleware',
    'mydjango.middleware.common.CommonMiddleware',
    'mydjango.middleware.csrf.CsrfViewMiddleware',
    'mydjango.contrib.auth.middleware.AuthenticationMiddleware',
    'mydjango.contrib.messages.middleware.MessageMiddleware',
    'mydjango.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mydjango.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'mydjango.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'mydjango.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'mydjango.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'mydjango.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh_Hans'  # en-us

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
